import type { LucideIcon } from "lucide-react";
import {
  BadgeCheck,
  Baby,
  BriefcaseBusiness,
  Brush,
  Candy,
  CookingPot,
  CupSoda,
  Droplets,
  Dumbbell,
  FileCheck,
  Flower2,
  HandHelping,
  Heart,
  Leaf,
  Milk,
  Package,
  MapPin,
  ScrollText,
  Scale,
  ShieldCheck,
  ShoppingBasket,
  Sparkles,
  Store,
  Truck,
  Users,
  Wheat,
} from "lucide-react";

import type { IconKey } from "@/components/landing/data";

export const iconMap: Record<IconKey, LucideIcon> = {
  droplets: Droplets,
  milk: Milk,
  candy: Candy,
  wheat: Wheat,
  flower: Flower2,
  leaf: Leaf,
  package: Package,
  cooking: CookingPot,
  scroll: ScrollText,
  sparkles: Sparkles,
  brush: Brush,
  cup: CupSoda,
  users: Users,
  baby: Baby,
  heart: Heart,
  dumbbell: Dumbbell,
  hand: HandHelping,
  briefcase: BriefcaseBusiness,
  store: Store,
  shopping: ShoppingBasket,
  scale: Scale,
  shield: ShieldCheck,
  badge: BadgeCheck,
  truck: Truck,
  pin: MapPin,
  file: FileCheck,
};
